apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ouvk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vzly-tenant/rhtap-demo-app/hacbs-test-project-ouvk@sha256:f5b8ca0a08733b3fc072ef56004a79fce33a2b68cba39375e58df5672370d563
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
